#!/bin/bash

_fail() {
	echo $1
	exit 1
}

_wait_for_vm_to_boot()
{
	_loops=0
	echo "Waiting for the box to come back up"
	while [ 1 ]
	do
		sleep 5
		ssh root@$1 uname -r 2> /dev/null && break
		_loops=$(( _loops + 1 ))
		[ "$_loops" -gt "10" ] && return 1
	done

	return 0
}
