name = "xfstest-btrfs"
description = "xfstest image for testing btrfs"
version = "0.0.3"
modules = []
groups = []
distro = "fedora-38"

[[packages]]
name = "acl"

[[packages]]
name = "attr"

[[packages]]
name = "bc"

[[packages]]
name = "cronie"

[[packages]]
name = "dbench"

[[packages]]
name = "e2fsprogs"

[[packages]]
name = "e2fsprogs-devel"

[[packages]]
name = "fio"

[[packages]]
name = "gawk"

[[packages]]
name = "gcc"

[[packages]]
name = "git"

[[packages]]
name = "indent"

[[packages]]
name = "libacl-devel"

[[packages]]
name = "libaio-devel"

[[packages]]
name = "libattr-devel"

[[packages]]
name = "libcap-devel"

[[packages]]
name = "libtool"

[[packages]]
name = "liburing-devel"

[[packages]]
name = "libuuid-devel"

[[packages]]
name = "lvm2"

[[packages]]
name = "make"

[[packages]]
name = "psmisc"

[[packages]]
name = "python3"

[[packages]]
name = "quota"

[[packages]]
name = "sed"

[[packages]]
name = "sqlite"

[[packages]]
name = "udftools"

[[packages]]
name = "xfsprogs"

[[packages]]
name = "xfsprogs-devel"

[[packages]]
name = "libblkid-devel"

[[packages]]
name = "zlib-devel"

[[packages]]
name = "libzstd-devel"

[[packages]]
name = "systemd-devel"

[[packages]]
name = "lzo-devel"

[[packages]]
name = "fsverity-utils"

[[packages]]
name = "fio-engine-libaio"

[[packages]]
name = "gdbm-devel"

[customizations]

[[customizations.user]]
name = "fsgqa"

[customizations.timezone]
[customizations.locale]
[customizations.firewall]
